# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.

[libraries]

# Defines library work
work.files = [
  'src/*.vhd',
]

# Defines library lib1
#lib1.files = [
#  'pkg1.vhd',
#  'tb_ent.vhd',
#]